/**
 * Magic 8ball response as as an array of strings
 */

module.exports = [
    "Well... Yeah. It's kinda obvious.",
    "Sure, I guess.",
    "How could I ever say no to you? :heart:",
    "Ye.",
    "Very, very likely",
    "I'm betting my life on it",
    "Yup yup",
    "Maybe. Perhaps. I guess.",
    "Yes. Well, yes *and* no.",
    "No. Well, yes *and* no.", ,
    "Just... I mean, if you want to?",
    "I suppose. It's not the first thing that comes to my mind though",
    "I *GUESS*",
    "I don't know, maybe?",
    "It's not *impossible*, it's just not likely.",
    "NO! NEVER!",
    "Uhm... I don't think so",
    "Yeah, no, definitely not.",
    "Not. A. Chance.",
    "No.",
    "GOD NO",
    "I am certain that is not the case, no.",
    "Oh, no no no no no. Just no.",
    "Ehh...",
    "I'm kinda busy here, can't you figure it out yourself?",
    "I don't think I wanna give my opinion on this.",
    "LEAVE ME ALONE REEEEEEE",
    "REEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
    "It Depends™",
    "On times like this, I like to ask myself: what would Jesus say?",
    "Great question. Just wonderful. I love it. Ask me again.",
    "Huh. Never thought of it that way. I'll sleep on it and get back to you tomorrow, 'k?",
    'Signs point to yes. Except that you were born an idiot, you will die an idiot, and nothing will change in-between.',
    'Without a doubt. Nah, I’m just messing with you, go shoot yourself.',
    'Outlook not so good. Especially since you’re so goddamn ugly.',
    'As If',
    'Ask Me If I Care',
    'Dumb Question Ask Another',
    'Forget About It',
    'In Your Dreams',
    'Not A Chance',
    'Obviously',
    'Oh Please',
    'Sure',
    'That\'s Ridiculous',
    'Well Maybe',
    'What Do You Think?',
    'Who Cares?',
    'Yeah Right',
    'You Wish',
    'You\'ve Got To Be Kidding...',
    'Yes',
    'It is certain',
    'It is decidedly so',
    'Without a doubt',
    'Yes definitely',
    'You may rely on it',
    'As I see it, yes',
    'Most likely',
    'Outlook good',
    'Signs point to yes',
    'Reply hazy try again',
    'Ask again later',
    'Better not tell you now',
    'Cannot predict now',
    'Concentrate and ask again',
    'Don\'t count on it',
    'My reply is no',
    'My sources say no',
    'Outlook not so good',
    'Very doubtful',
    'Hold on, my wifi connection is going out.',
]