/**
 * An array of (strings) insulting sentences
 */
module.exports = [
	"I hear the only place you're ever invited is outside.",
	"I'd offer you some gum but your smiles got plenty of it.",
	"Your body fat is about as evenly distributed as wealth in the US economy.",
	"You're like dobby from harry potter, only people won't be sad when you die in the seventh book.",
	"If I asked you about your cock it wouldn't be a very long conversation.",
	"You have the kinds of looks that make people talk about your personality.",
	"You look like the result of pressing random on the character creation menu.",
	"You look like the after picture of a meth ad.",
	"Even the shower doesn't want to see you naked.",
	"I bet you wear a nose ring because no one wants to put one on your finger.",
	"When the airforce needs extra landing space they should just rent out your forehead.",
	"If laughter is the best medicine, your face must be curing the world.",
	"It looks like your face caught fire and someone tried to put it out with a hammer.",
	"Your family tree must be a cactus because everyone on it is a prick.",
	"Save your breath - youre going to need it to blow up your date.",
	"You're proof evolution can go in reverse.",
	"When you were born, the doctor came out to the waiting room and said to your dad, \"I'm very sorry. We did everything we could. But he pulled through.\"",
	"You've got less meat in your pants than there is in a vegetarian restaurant.",
	"I wasn't born with enough middle fingers to let you know how I feel about you.",
	"Your birth certificate is an apology letter from the condom factory.",
	"You're about as useful as a vibrator with no batteries.",
	"Fake hair, fake nails, fake smile. Are you sure you weren't made in China?",
	"You’re my favorite person besides every other person I’ve ever met.",
	"Did your parents have any children that lived?",
	"I envy people who have never met you.",
	"At least my mom pretends to love me",
	"Bards will chant parables of your legendary stupidity for centuries, $mention",
	"Don't play hard to get when you are hard to want",
	"Don't you worry your pretty little head about it. The operative word being little. Not pretty.",
	"Get a damn life you uncultured swine.",
	"Goddamn did your parents dodge a bullet when they abandoned you.",
	"I can't even call you ugly, because nature has already beaten me to it.",
	"I cant wait to forget you.",
	"I don't have the time, or the crayons to explain this to you.",
	"I hate the way you laugh.",
	"I hope you win the lottery and lose your ticket.",
	"I once smelled a dog fart that had more cunning, personality, and charm than you.",
	"I shouldn't roast you, I can't imagine the pain you go through with that face!",
	"I wonder if you'd be able to speak more clearly if your parents were second cousins instead of first.",
	"I would challenge you to a battle of wits, but it seems you come unarmed",
	"I would rather be friends with Ajit Pai than you.",
	"I'd love to stay and chat but I'd rather have type-2 diabetes",
	"I'm just surprised you haven't yet retired from being a butt pirate.",
	"I'm not mad. I'm just... disappointed.",
	"I've never met someone who's at once so thoughtless, selfish, and uncaring of other people's interests, while also having such lame and boring interests of his own. You don't have friends, because you shouldn't.",
	"I’m betting your keyboard is filthy from all that Cheeto-dust finger typing, you weaboo shut in. ",
	"If 'unenthusiastic handjob' had a face, your profile picture would be it.",
	"If there was a single intelligent thought in your head it would have died from loneliness.",
	"If you were a potato you'd be a stupid potato.",
	"If you were an inanimate object, you'd be a participation trophy.",
	"If you where any stupider we'd have to water you",
	"Jesus Christ it looks like your face was on fire and someone tried to put it out with an ice pick",
	"May the fleas of ten thousand camels live happily upon your buttocks",
	"Maybe if you eat all that makeup you will be beautiful on the inside.",
	"Mr. Rogers would be disappointed in you.",
	"Not even your dog loves you. He's just faking it.",
	"Once upon a time, Santa Clause was asked what he thought of your mom, your sister and your grandma, and thus his catchphrase was born.",
	"People don't even pity you.",
	"People like you are the reason God doesn't talk to us anymore",
	"Take my lowest priority and put yourself beneath it.",
	"The IQ test only goes down to zero but you make a really compelling case for negative numbers",
	"The only thing you're screwing is natural selection",
	"There are two ugly people in this chat, and you're both of them.",
	"There will never be enough middle fingers in this world for $mention",
	"They don't make a short enough bus in the Continental United States for a person like you.",
	"Those aren't acne scars, those are marks from the hanger.",
	"Twelve must be difficult for you. I don’t mean BEING twelve, I mean that being your IQ.",
	"We all dislike you, but not quite enough that we bother to think about you.",
	"When you die, people will struggle to think of nice things to say about you.",
	"Where'd ya get those pants? The toilet store?",
	"Why do you sound like you suck too many cocks?",
	"Why don’t you crawl back to whatever micro-organism cesspool you came from, and try not to breath any of our oxygen on the way there",
	"You are a pizza burn on the roof of the world's mouth.",
	"You are a stupid.",
	"You are dumber than a block of wood and not nearly as useful",
	"You are like the end piece of bread in a loaf, everyone touches you but no one wants you",
	"You have a face made for radio",
	"You have the face of a bulldog licking piss off a stinging nettle.",
	"You know they say 90% of dust is dead human skin? That's what you are to me.",
	"You know, one of the many, many things that confuses me about you is that you remain unmurdered.",
	"You look like your father would be disappointed in you. If he stayed.",
	"You losing your virginity is like a summer squash growing in the middle of winter. Never happening.",
	"You may think people like being around you- but remember this: there is a difference between being liked and being tolerated.",
	"You might want to get a colonoscopy for all that butthurt",
	"You need to go up to your daddy, get on your knees and apologize to each and every brother and sister that didn't make it to your mother's egg before you",
	"You stuck up, half-witted, scruffy looking nerf herder!",
	"You're an example of why animals eat their young.",
	"You're impossible to underestimate",
	"You're kinda like Rapunzel except instead of letting down your hair you let down everyone in your life",
	"You're like a penny on the floor of a public restroom - filthy, untouchable and practically worthless.",
	"You're like a square blade, all edge and no point.",
	"You're looking well for a man twice your age! Any word on the aneurism?",
	"You're not pretty enough to be this dumb",
	"You're objectively unattractive.",
	"You're so dense, light bends around you.",
	"You're so salty you would sink in the Dead Sea",
	"You're so stupid you couldn't pour piss out of a boot if the directions were written on the heel",
	"You're ugly when you cry.",
	"Your birth certificate is an apology letter from the abortion clinic.",
	"Your memes are trash.",
	"Your mother may have told you that you could be anything you wanted, but a douchebag wasn't what she meant.",
	"Your mother was a hamster, and your father reeks of elderberries!",
	"I’ve seen people like you before, but I had to pay admission.",
	"You’re so fat you could sell shade.",
	"Which sexual position produces the ugliest children? Ask your mother.",
	"Roses are red violets are blue, God made me pretty, what happened to you?",
	"Dumbass!",
	"You're so poor I saw you kicking a can across the street. I asked you what you were doing you said moving.",
	"We can always tell when you are lying. Your lips move.",
	"The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
	"Your dad's condom is a bigger than your personality.",
	"You married Barney.",
	"Oh my God, look at you. Anyone else hurt in the accident.",
	"Yo mama so ugly when she looked in the mirror her reflection walked away.",
	"Your so weak that you can't rip a piece of paper.",
	"You so ugly when who were born the doctor threw you out the window and the window threw you back.",
	"I'm busy now. Can I ignore you some other time?",
	"If ugliness were bricks, you would be the Great Wall of China.",
	"At least my mom pretends to love me",
	"May both sides of your pillow be uncomfortably warm.",
	"I’d agree with you but then we’d both be wrong.",
	"Keep rolling your eyes, you might eventually find a brain.",
	"I’m glad to see you’re not letting education get in the way of your ignorance.",
	"Don’t be ashamed of who you are. That’s your parent’s job.",
	"I get so emotional when you're not around. That emotion is happiness.",
	"You are so ugly that when your mom dropped you off at school, she got a ticket for littering.",
	"I’m jealous of all the people who haven’t met you.",
	"You are the human version of period cramps.",
	"You've only got 2 brain cells and they are both fighting for 3rd place.",
	"Isn’t it dangerous to use your whole vocabulary in one sentence?",
	"I told my therapist about you.",
	"I thought of you today. It reminded me to take out the trash.",
	"Calling you an idiot would be an insult to all the stupid people.",
	"You must have been born on a highway. That’s where most accidents happen.",
	"If genius skips a generation, your children will be brilliant.",
]